const OMNI_SEED_DATA: Array<{id: string; category: string; name: string}> = [
  { id: "rec0Vh9bASzO7HcRc_hr", category: "OMNI - HR Support", name: "Hospital Employee Communications" },
  { id: "rec0Vh9bASzO7HcRc_rx", category: "OMNI - Pharmacy", name: "Pharmacy Contract Analysis" },
  { id: "rec0Vh9bASzO7HcRc_med", category: "OMNI - Medical", name: "Hospital Domestic Network Optimization" },
  { id: "rec0Vh9bASzO7HcRc_ph", category: "OMNI - Population Health", name: "Weight Loss Programs" },
  { id: "rec0Vh9bASzO7HcRc_ci", category: "OMNI - Care Intervention", name: "Transparency Pricing Tools" },
  { id: "rec0er9za9KkCJJOz_med", category: "OMNI - Medical", name: "Spousal Coverage Strategy" },
  { id: "rec1XZGaRFtHbLW8v_hr", category: "OMNI - HR Support", name: "Leave Management Vendor Selection" },
  { id: "rec1XZGaRFtHbLW8v_med", category: "OMNI - Medical", name: "International Benefits Consulting" },
  { id: "rec2bgolhNjPWf2Ua_comp", category: "OMNI - Compliance", name: "Healthcare Reform Impact Analysis" },
  { id: "rec2bgolhNjPWf2Ua_hr", category: "OMNI - HR Support", name: "Benefits Administration Vendor Selection" },
  { id: "rec2bgolhNjPWf2Ua_rx", category: "OMNI - Pharmacy", name: "Hospital Pharmacy Management and Purchasing" },
  { id: "rec2bgolhNjPWf2Ua_anc", category: "OMNI - Ancillary", name: "Self-insured Options for Dental Plans" },
  { id: "rec2bgolhNjPWf2Ua_med", category: "OMNI - Medical", name: "Dependent Eligibility Management" },
  { id: "rec2bgolhNjPWf2Ua_ph", category: "OMNI - Population Health", name: "Incentivized Physician Engagement" },
  { id: "rec2bgolhNjPWf2Ua_ci", category: "OMNI - Care Intervention", name: "Hemophilia Management" },
  { id: "rec2lGsP7LFMKUDVU_comp", category: "OMNI - Compliance", name: "Discrimination Exposure Review" },
  { id: "rec2lGsP7LFMKUDVU_hr", category: "OMNI - HR Support", name: "Benefit Resource Center" },
  { id: "rec2lGsP7LFMKUDVU_rx", category: "OMNI - Pharmacy", name: "Guaranteed Average Script Pricing" },
  { id: "rec2lGsP7LFMKUDVU_anc", category: "OMNI - Ancillary", name: "Packaged Ancillary Program Savings" },
  { id: "rec2lGsP7LFMKUDVU_med", category: "OMNI - Medical", name: "Contribution Modeling" },
  { id: "rec2lGsP7LFMKUDVU_ph", category: "OMNI - Population Health", name: "Improving Behavioral Health Diagnosis & Access" },
  { id: "rec2lGsP7LFMKUDVU_ci", category: "OMNI - Care Intervention", name: "Disease Management Program Review" },
  { id: "rec35qZl06Flm7YKE_med", category: "OMNI - Medical", name: "Review of State Mandated Benefits" },
  { id: "rec3LfKgSiD8kccIk_med", category: "OMNI - Medical", name: "Proprietary Stop Loss Benchmarking" },
  { id: "rec4VtIvlldADCTYI_comp", category: "OMNI - Compliance", name: "Compliance Check List Review" },
  { id: "rec4VtIvlldADCTYI_hr", category: "OMNI - HR Support", name: "Administrative Services Vendor Selection" },
  { id: "rec4VtIvlldADCTYI_rx", category: "OMNI - Pharmacy", name: "Customized PBM Management" },
  { id: "rec4VtIvlldADCTYI_anc", category: "OMNI - Ancillary", name: "Life and Disability SIC Codes Alignment" },
  { id: "rec4VtIvlldADCTYI_med", category: "OMNI - Medical", name: "Alternative Funding Analysis" },
  { id: "rec4VtIvlldADCTYI_ph", category: "OMNI - Population Health", name: "Carrier Based Wellness Program" },
  { id: "rec4VtIvlldADCTYI_ci", category: "OMNI - Care Intervention", name: "CGMs for Type 1 Diabetes" },
  { id: "rec7jwDSa0mD8VaNR_hr", category: "OMNI - HR Support", name: "USI Mobile App MyBenefits2Go" },
  { id: "rec7jwDSa0mD8VaNR_med", category: "OMNI - Medical", name: "Out of Country Travel Benefits" },
  { id: "rec7oIhAZgGO6PMkd_hr", category: "OMNI - HR Support", name: "Hospital Specific Benchmarking of Benefit Plans" },
  { id: "rec7oIhAZgGO6PMkd_rx", category: "OMNI - Pharmacy", name: "Step Therapy Programs" },
  { id: "rec7oIhAZgGO6PMkd_med", category: "OMNI - Medical", name: "ICHRA Plans" },
  { id: "rec7oIhAZgGO6PMkd_ph", category: "OMNI - Population Health", name: "Wellness Contests and Resources" },
  { id: "rec8yjQD6zZkdh9Jm_med", category: "OMNI - Medical", name: "Supplemental Reimbursement Strategies" },
  { id: "rec9um9fOsmFeD7Fa_med", category: "OMNI - Medical", name: "USI Preferred TPA Panel" },
  { id: "recAFIzK0SHAZJWGV_comp", category: "OMNI - Compliance", name: "Comprehensive Compliance review" },
  { id: "recAFIzK0SHAZJWGV_hr", category: "OMNI - HR Support", name: "Annual Service Calendar" },
  { id: "recAFIzK0SHAZJWGV_rx", category: "OMNI - Pharmacy", name: "Establishing Appropriate Quantity Limits" },
  { id: "recAFIzK0SHAZJWGV_anc", category: "OMNI - Ancillary", name: "LTD Solutions for Government Plans" },
  { id: "recAFIzK0SHAZJWGV_med", category: "OMNI - Medical", name: "Certified IBNR Analysis" },
  { id: "recAFIzK0SHAZJWGV_ph", category: "OMNI - Population Health", name: "CORE Health Action Plan" },
  { id: "recAFIzK0SHAZJWGV_ci", category: "OMNI - Care Intervention", name: "Diabetes Management for Type 2 Diabetes" },
  { id: "recBDdVVoMbhh4swb_hr", category: "OMNI - HR Support", name: "Hospital Compensation Consulting" },
  { id: "recBDdVVoMbhh4swb_rx", category: "OMNI - Pharmacy", name: "Narrow Pharmacy Network" },
  { id: "recBDdVVoMbhh4swb_anc", category: "OMNI - Ancillary", name: "Voluntary Benefits Strategy - Short Term Disability Insurance" },
  { id: "recBDdVVoMbhh4swb_med", category: "OMNI - Medical", name: "High Deductible Plan Implementation" },
  { id: "recBDdVVoMbhh4swb_ph", category: "OMNI - Population Health", name: "USI CORE HEALTH Strategy" },
  { id: "recBDdVVoMbhh4swb_ci", category: "OMNI - Care Intervention", name: "Telemedicine" },
  { id: "recBz4IJjd97rXYTM_med", category: "OMNI - Medical", name: "USI Market Leverage" },
  { id: "recFnX6zCEibajoUW_hr", category: "OMNI - HR Support", name: "Open Enrollment Engagement Strategies" },
  { id: "recFnX6zCEibajoUW_med", category: "OMNI - Medical", name: "Negotiate Carrier Performance Guarantees" },
  { id: "recG6wuSEKqUjEPWj_med", category: "OMNI - Medical", name: "Quarterly Claims Reviews" },
  { id: "recJGHXeH4Fc36ZAx_hr", category: "OMNI - HR Support", name: "Transitioning from Broker-Owned BenAdmin " },
  { id: "recJGHXeH4Fc36ZAx_med", category: "OMNI - Medical", name: "Network Discount Analysis" },
  { id: "recJvHSaOo35TNrbV_comp", category: "OMNI - Compliance", name: "Legislative & Regulatory Updates" },
  { id: "recJvHSaOo35TNrbV_hr", category: "OMNI - HR Support", name: "Decision Support Tools" },
  { id: "recJvHSaOo35TNrbV_rx", category: "OMNI - Pharmacy", name: "Incentivized Copay Structure" },
  { id: "recJvHSaOo35TNrbV_anc", category: "OMNI - Ancillary", name: "Self-insured Options for Vision Plans" },
  { id: "recJvHSaOo35TNrbV_med", category: "OMNI - Medical", name: "Evaluate New Hire Waiting Periods" },
  { id: "recJvHSaOo35TNrbV_ph", category: "OMNI - Population Health", name: "Mind Body Money" },
  { id: "recJvHSaOo35TNrbV_ci", category: "OMNI - Care Intervention", name: "Medical Second Opinion" },
  { id: "recKysyxEXXoCVzNx_comp", category: "OMNI - Compliance", name: "Reporting and Disclosure Requirements" },
  { id: "recKysyxEXXoCVzNx_hr", category: "OMNI - HR Support", name: "Employee Benefits Communication and Education" },
  { id: "recKysyxEXXoCVzNx_rx", category: "OMNI - Pharmacy", name: "Independent Prior Authorization" },
  { id: "recKysyxEXXoCVzNx_anc", category: "OMNI - Ancillary", name: "Voluntary Benefits Strategy - Dental Insurance" },
  { id: "recKysyxEXXoCVzNx_med", category: "OMNI - Medical", name: "Evaluating Captive Management Solutions" },
  { id: "recKysyxEXXoCVzNx_ph", category: "OMNI - Population Health", name: "Pathways to Parenthood" },
  { id: "recKysyxEXXoCVzNx_ci", category: "OMNI - Care Intervention", name: "MSK Disorders Management" },
  { id: "recQSBxoMlUYP1V2a_med", category: "OMNI - Medical", name: "PEO Vendor Selection" },
  { id: "recQnxskbOKu2JXpj_comp", category: "OMNI - Compliance", name: "Workshops, Seminars and Webinars" },
  { id: "recQnxskbOKu2JXpj_hr", category: "OMNI - HR Support", name: "Financial Wellness Vendor Selection " },
  { id: "recQnxskbOKu2JXpj_rx", category: "OMNI - Pharmacy", name: "International Prescription Drug Sourcing" },
  { id: "recQnxskbOKu2JXpj_anc", category: "OMNI - Ancillary", name: "Voluntary Benefits Strategy - Life Insurance" },
  { id: "recQnxskbOKu2JXpj_med", category: "OMNI - Medical", name: "Hidden Fee Review for Self-Funded Plans " },
  { id: "recQnxskbOKu2JXpj_ph", category: "OMNI - Population Health", name: "Predictive Modeling" },
  { id: "recQnxskbOKu2JXpj_ci", category: "OMNI - Care Intervention", name: "On-site Care Strategies" },
  { id: "recRUX32O5n5fpUI9_comp", category: "OMNI - Compliance", name: "Client Specific Assistance on Compliance Issues" },
  { id: "recRUX32O5n5fpUI9_hr", category: "OMNI - HR Support", name: "1095 ACA Reporting Vendor Selection" },
  { id: "recRUX32O5n5fpUI9_rx", category: "OMNI - Pharmacy", name: "Auditing Pharmacy Expense" },
  { id: "recRUX32O5n5fpUI9_anc", category: "OMNI - Ancillary", name: "Dental Discount Analysis" },
  { id: "recRUX32O5n5fpUI9_med", category: "OMNI - Medical", name: "Actuarial Valuation of Retiree Health Plans" },
  { id: "recRUX32O5n5fpUI9_ph", category: "OMNI - Population Health", name: "Biometric Screening" },
  { id: "recRUX32O5n5fpUI9_ci", category: "OMNI - Care Intervention", name: "Cancer Care Management" },
  { id: "recRcFOYF0mCK9qyG_hr", category: "OMNI - HR Support", name: "Medical Claims Audit" },
  { id: "recRcFOYF0mCK9qyG_med", category: "OMNI - Medical", name: "Large Claim Review and Forecasting" },
  { id: "recSJSkYpLYZIhjrq_comp", category: "OMNI - Compliance", name: "Hospital Specific Assistance on Compliance Issues" },
  { id: "recSJSkYpLYZIhjrq_hr", category: "OMNI - HR Support", name: "Compensation Analysis" },
  { id: "recSJSkYpLYZIhjrq_rx", category: "OMNI - Pharmacy", name: "Identification of Wasteful Drug Spending" },
  { id: "recSJSkYpLYZIhjrq_anc", category: "OMNI - Ancillary", name: "Self-insured Options for STD Plans" },
  { id: "recSJSkYpLYZIhjrq_med", category: "OMNI - Medical", name: "Early Renewal Delivery" },
  { id: "recSJSkYpLYZIhjrq_ph", category: "OMNI - Population Health", name: "Incentivized Physician Engagement for Spouses" },
  { id: "recSJSkYpLYZIhjrq_ci", category: "OMNI - Care Intervention", name: "Hospital Domestic Care Management Programs" },
  { id: "recSRRdF8fQkSZa0U_med", category: "OMNI - Medical", name: "Plan Design Modeling" },
  { id: "reca6ycDasJvLOQpi_med", category: "OMNI - Medical", name: "Reference Based Pricing" },
  { id: "recc9bKNSROomHPOp_hr", category: "OMNI - HR Support", name: "Medicare Education & Enrollment Consulting" },
  { id: "recc9bKNSROomHPOp_med", category: "OMNI - Medical", name: "Minimal Essential and Minimal Value Coverages" },
  { id: "recf5LTHekLwHG9Ed_med", category: "OMNI - Medical", name: "Tiered Network Incentive Strategies" },
  { id: "recfhh9GFFEzXwaiV_hr", category: "OMNI - HR Support", name: "Work Opportunity Tax Credit (WOTC)" },
  { id: "recfhh9GFFEzXwaiV_med", category: "OMNI - Medical", name: "PEO Exit Strategies" },
  { id: "recgjCODJeMtbyXzc_hr", category: "OMNI - HR Support", name: "HCM Vendor Selection" },
  { id: "recgjCODJeMtbyXzc_rx", category: "OMNI - Pharmacy", name: "Manufacturer Pharmacy Assistance Programs (PAP)" },
  { id: "recgjCODJeMtbyXzc_anc", category: "OMNI - Ancillary", name: "Voluntary Benefits Strategy - Long Term Disability Coverage" },
  { id: "recgjCODJeMtbyXzc_med", category: "OMNI - Medical", name: "High Deductible Funding Strategies" },
  { id: "recgjCODJeMtbyXzc_ph", category: "OMNI - Population Health", name: "Third-Party Based Wellness Program" },
  { id: "recgjCODJeMtbyXzc_ci", category: "OMNI - Care Intervention", name: "Pharmacogenetic (PGx) Testing" },
  { id: "recnP2Q52Dmt1CvKB_hr", category: "OMNI - HR Support", name: "HR Compliance Platform: Client Cloud from Zywave" },
  { id: "recnP2Q52Dmt1CvKB_rx", category: "OMNI - Pharmacy", name: "Strategic Drug Exclusions" },
  { id: "recnP2Q52Dmt1CvKB_med", category: "OMNI - Medical", name: "Improve Network Utilization" },
  { id: "recpGrJQjuPwIRcye_hr", category: "OMNI - HR Support", name: "Leave Management and Return to Work Strategies" },
  { id: "recpGrJQjuPwIRcye_rx", category: "OMNI - Pharmacy", name: "USI Clear Options Rx: Managed Pharmacy Strategy" },
  { id: "recpGrJQjuPwIRcye_med", category: "OMNI - Medical", name: "International Assignees Benefits" },
  { id: "recrAk9AdLWFVyOWi_med", category: "OMNI - Medical", name: "USI Stop Loss Consortium" },
  { id: "recvdmcUZGRRbhtAy_comp", category: "OMNI - Compliance", name: "Comprehensive Employer Guides and Toolkits" },
  { id: "recvdmcUZGRRbhtAy_hr", category: "OMNI - HR Support", name: "Benchmarking of Benefit Plans" },
  { id: "recvdmcUZGRRbhtAy_rx", category: "OMNI - Pharmacy", name: "Gene Therapy Coverage Strategies" },
  { id: "recvdmcUZGRRbhtAy_anc", category: "OMNI - Ancillary", name: "Negotiate Ancillary Multi-Year Rate Guarantees" },
  { id: "recvdmcUZGRRbhtAy_med", category: "OMNI - Medical", name: "Comprehensive Underwriting Review" },
  { id: "recvdmcUZGRRbhtAy_ph", category: "OMNI - Population Health", name: "Employer Tobacco Policies" },
  { id: "recvdmcUZGRRbhtAy_ci", category: "OMNI - Care Intervention", name: "Direct Primary Care" },
];

const OMNI_ID_MAPPING: Record<string, string[]> = {
  "rec0Vh9bASzO7HcRc": ["rec0Vh9bASzO7HcRc_hr", "rec0Vh9bASzO7HcRc_rx", "rec0Vh9bASzO7HcRc_med", "rec0Vh9bASzO7HcRc_ph", "rec0Vh9bASzO7HcRc_ci"],
  "rec0er9za9KkCJJOz": ["rec0er9za9KkCJJOz_med"],
  "rec1XZGaRFtHbLW8v": ["rec1XZGaRFtHbLW8v_hr", "rec1XZGaRFtHbLW8v_med"],
  "rec2bgolhNjPWf2Ua": ["rec2bgolhNjPWf2Ua_comp", "rec2bgolhNjPWf2Ua_hr", "rec2bgolhNjPWf2Ua_rx", "rec2bgolhNjPWf2Ua_anc", "rec2bgolhNjPWf2Ua_med", "rec2bgolhNjPWf2Ua_ph", "rec2bgolhNjPWf2Ua_ci"],
  "rec2lGsP7LFMKUDVU": ["rec2lGsP7LFMKUDVU_comp", "rec2lGsP7LFMKUDVU_hr", "rec2lGsP7LFMKUDVU_rx", "rec2lGsP7LFMKUDVU_anc", "rec2lGsP7LFMKUDVU_med", "rec2lGsP7LFMKUDVU_ph", "rec2lGsP7LFMKUDVU_ci"],
  "rec35qZl06Flm7YKE": ["rec35qZl06Flm7YKE_med"],
  "rec3LfKgSiD8kccIk": ["rec3LfKgSiD8kccIk_med"],
  "rec4VtIvlldADCTYI": ["rec4VtIvlldADCTYI_comp", "rec4VtIvlldADCTYI_hr", "rec4VtIvlldADCTYI_rx", "rec4VtIvlldADCTYI_anc", "rec4VtIvlldADCTYI_med", "rec4VtIvlldADCTYI_ph", "rec4VtIvlldADCTYI_ci"],
  "rec7jwDSa0mD8VaNR": ["rec7jwDSa0mD8VaNR_hr", "rec7jwDSa0mD8VaNR_med"],
  "rec7oIhAZgGO6PMkd": ["rec7oIhAZgGO6PMkd_hr", "rec7oIhAZgGO6PMkd_rx", "rec7oIhAZgGO6PMkd_med", "rec7oIhAZgGO6PMkd_ph"],
  "rec8yjQD6zZkdh9Jm": ["rec8yjQD6zZkdh9Jm_med"],
  "rec9um9fOsmFeD7Fa": ["rec9um9fOsmFeD7Fa_med"],
  "recAFIzK0SHAZJWGV": ["recAFIzK0SHAZJWGV_comp", "recAFIzK0SHAZJWGV_hr", "recAFIzK0SHAZJWGV_rx", "recAFIzK0SHAZJWGV_anc", "recAFIzK0SHAZJWGV_med", "recAFIzK0SHAZJWGV_ph", "recAFIzK0SHAZJWGV_ci"],
  "recBDdVVoMbhh4swb": ["recBDdVVoMbhh4swb_hr", "recBDdVVoMbhh4swb_rx", "recBDdVVoMbhh4swb_anc", "recBDdVVoMbhh4swb_med", "recBDdVVoMbhh4swb_ph", "recBDdVVoMbhh4swb_ci"],
  "recBz4IJjd97rXYTM": ["recBz4IJjd97rXYTM_med"],
  "recFnX6zCEibajoUW": ["recFnX6zCEibajoUW_hr", "recFnX6zCEibajoUW_med"],
  "recG6wuSEKqUjEPWj": ["recG6wuSEKqUjEPWj_med"],
  "recJGHXeH4Fc36ZAx": ["recJGHXeH4Fc36ZAx_hr", "recJGHXeH4Fc36ZAx_med"],
  "recJvHSaOo35TNrbV": ["recJvHSaOo35TNrbV_comp", "recJvHSaOo35TNrbV_hr", "recJvHSaOo35TNrbV_rx", "recJvHSaOo35TNrbV_anc", "recJvHSaOo35TNrbV_med", "recJvHSaOo35TNrbV_ph", "recJvHSaOo35TNrbV_ci"],
  "recKysyxEXXoCVzNx": ["recKysyxEXXoCVzNx_comp", "recKysyxEXXoCVzNx_hr", "recKysyxEXXoCVzNx_rx", "recKysyxEXXoCVzNx_anc", "recKysyxEXXoCVzNx_med", "recKysyxEXXoCVzNx_ph", "recKysyxEXXoCVzNx_ci"],
  "recQSBxoMlUYP1V2a": ["recQSBxoMlUYP1V2a_med"],
  "recQnxskbOKu2JXpj": ["recQnxskbOKu2JXpj_comp", "recQnxskbOKu2JXpj_hr", "recQnxskbOKu2JXpj_rx", "recQnxskbOKu2JXpj_anc", "recQnxskbOKu2JXpj_med", "recQnxskbOKu2JXpj_ph", "recQnxskbOKu2JXpj_ci"],
  "recRUX32O5n5fpUI9": ["recRUX32O5n5fpUI9_comp", "recRUX32O5n5fpUI9_hr", "recRUX32O5n5fpUI9_rx", "recRUX32O5n5fpUI9_anc", "recRUX32O5n5fpUI9_med", "recRUX32O5n5fpUI9_ph", "recRUX32O5n5fpUI9_ci"],
  "recRcFOYF0mCK9qyG": ["recRcFOYF0mCK9qyG_hr", "recRcFOYF0mCK9qyG_med"],
  "recSJSkYpLYZIhjrq": ["recSJSkYpLYZIhjrq_comp", "recSJSkYpLYZIhjrq_hr", "recSJSkYpLYZIhjrq_rx", "recSJSkYpLYZIhjrq_anc", "recSJSkYpLYZIhjrq_med", "recSJSkYpLYZIhjrq_ph", "recSJSkYpLYZIhjrq_ci"],
  "recSRRdF8fQkSZa0U": ["recSRRdF8fQkSZa0U_med"],
  "reca6ycDasJvLOQpi": ["reca6ycDasJvLOQpi_med"],
  "recc9bKNSROomHPOp": ["recc9bKNSROomHPOp_hr", "recc9bKNSROomHPOp_med"],
  "recf5LTHekLwHG9Ed": ["recf5LTHekLwHG9Ed_med"],
  "recfhh9GFFEzXwaiV": ["recfhh9GFFEzXwaiV_hr", "recfhh9GFFEzXwaiV_med"],
  "recgjCODJeMtbyXzc": ["recgjCODJeMtbyXzc_hr", "recgjCODJeMtbyXzc_rx", "recgjCODJeMtbyXzc_anc", "recgjCODJeMtbyXzc_med", "recgjCODJeMtbyXzc_ph", "recgjCODJeMtbyXzc_ci"],
  "recnP2Q52Dmt1CvKB": ["recnP2Q52Dmt1CvKB_hr", "recnP2Q52Dmt1CvKB_rx", "recnP2Q52Dmt1CvKB_med"],
  "recpGrJQjuPwIRcye": ["recpGrJQjuPwIRcye_hr", "recpGrJQjuPwIRcye_rx", "recpGrJQjuPwIRcye_med"],
  "recrAk9AdLWFVyOWi": ["recrAk9AdLWFVyOWi_med"],
  "recvdmcUZGRRbhtAy": ["recvdmcUZGRRbhtAy_comp", "recvdmcUZGRRbhtAy_hr", "recvdmcUZGRRbhtAy_rx", "recvdmcUZGRRbhtAy_anc", "recvdmcUZGRRbhtAy_med", "recvdmcUZGRRbhtAy_ph", "recvdmcUZGRRbhtAy_ci"],
};

export { OMNI_SEED_DATA, OMNI_ID_MAPPING };
